import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import '@/app/globals.css'
import Header from "@/app/components/header/page";
import DropDown from "@/app/components/drop_down/page";
import { EstadoProvider } from "./components/state_provider/page";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "cesarFsjunior.com",
  description: "Generated by create next app",
  icons: { 
    icon: "/favicon.ico"
  }
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-br" className={roboto.variable}>
      <body className={`bg-background text-foreground ${roboto.className} min-h-screen`}>
        <EstadoProvider>
          <Header />
          <DropDown />
        </EstadoProvider>
        {children}
      </body>
    </html>
  );
}
