import type { Metadata } from "next";
import '@/app/globals.css'
import Header from "./components/header/page";

export const metadata: Metadata = {
  title: "Blog cSj",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="pt-br">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
